### PR TITLE
Version 0.10a, merged console and user to a single script. 

### PR DESCRIPTION
**Pull request by rizwank**
I'm not the best at github pull requests, so apologies if this is done the wrong way.

### CODE REVIEW

**Comment by mr-c** [comment]
I can't get this to be recognized as a userscript by Chrome via the drag-n-drop to chrome://extensions method :-/

**Comment by adamhwang** [comment]
I think it's because it's no longer .user.js

**Comment by mr-c** [comment]
@adamhwang Bingo; renaming the file did the trick

**Comment by adamhwang** [comment]
Thanks for the PR @rizwank.  I like the change, but I don't like losing all our change sets.  Could you make the change on .user.js only and then turn .console.js into a symlink to the gm script?  That way linking directly to the .user.js file can still be recognized and we would preserve the changes at least on the gm script.

**Pull request closed without merging**
