### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by bench-marc**
* fix momondo and skyscanner urls
* change wheretocredit protocol

### CODE REVIEW

**Comment by seththeriault** [comment]
I think these changes were already committed to master by @adamhwang 10 days ago. They are excellent!

**Comment by adamhwang** [comment]
@bench-marc can you rebase to resolve conflicts please?

**Comment by bench-marc** [comment]
conflicts resolved

**Comment by adamhwang** [comment]
Thank you @bench-marc!

**Pull request merged**
