### PR TITLE
Fix DL/AA and add AS/VX support

### PR DESCRIPTION
**Pull request by powerivq**
This PR fixes:
1. Delta when attempting to price a non-DL airline.
2. AA (it's not working now)
3. Add Alaska/Virgin America support

### CODE REVIEW

**Comment by powerivq** [comment]
@SteppoFF Do you mind taking a look?

**Comment by seththeriault** [comment]
Eliminating the "cabin" parameter from DL URLs breaks the proper pricing of Delta C+/PS fares (and possibly BE/MC ones) addressed in #28. As an example, when linking from a DTW-NRT PS fare, a Delta One fare will be displayed instead.

**Comment by seththeriault** [comment]
One approach for harmonious co-existence would be to add a setting for  "non-DL airline on DL":

```
--- ita-matrix-powertools.user.js	2018-01-05 21:52:52.000000000 -0500
+++ ita-matrix-powertools.user.js.nondl-on-dl	2018-01-05 21:54:41.000000000 -0500
@@ -149,6 +149,8 @@
 mptUsersettings["lhEdition"] = "US-gb"; // sets the local edition of Lufthansa
 mptUsersettings["lxEdition"] = "us_en"; // sets the local edition of Swiss
 
+mptUsersettings["nonDeltaAirlineOnDL"] = 0; // trying to ticket a non-DL airline on DL site?
+
 // *** DO NOT CHANGE BELOW THIS LINE***/
 // General settings
 var mptSettings = new Object();
@@ -202,6 +204,7 @@
     mptUsersettings["laEdition"] = (mptSavedUsersettings["laEdition"] === undefined ? mptUsersettings["laEdition"] : mptSavedUsersettings["laEdition"]);
     mptUsersettings["lhEdition"] = (mptSavedUsersettings["lhEdition"] === undefined ? mptUsersettings["lhEdition"] : mptSavedUsersettings["lhEdition"]);
     mptUsersettings["lxEdition"] = (mptSavedUsersettings["lxEdition"] === undefined ? mptUsersettings["lxEdition"] : mptSavedUsersettings["lxEdition"]);
+    mptUsersettings["nonDeltaAirlineOnDL"] = (mptSavedUsersettings["nonDeltaAirlineOnDL"] === undefined ? mptUsersettings["nonDeltaAirlineOnDL"] : mptSavedUsersettings["nonDeltaAirlineOnDL"]);
   }
 }
 
@@ -367,6 +370,7 @@
     str +='<div id="mptlaEdition" style="width:33%;float:left;">LAN Edition:<label style="cursor:pointer;">'+printSettingsvalue("laEdition")+'</label></div>';
     str +='<div id="mptlhEdition" style="width:33%;float:left;">Lufthansa Edition:<label style="cursor:pointer;">'+printSettingsvalue("lhEdition")+'</label></div>';
     str +='<div id="mptlxEdition" style="width:33%;float:left;">Swiss Edition:<label style="cursor:pointer;">'+printSettingsvalue("lxEdition")+'</label></div>';
+    str +='<div id="mptnonDeltaAirlineOnDL" style="width:33%;float:left;">Ticket non-DL on DL?:<label style="cursor:pointer;">'+printSettingsvalue("nonDeltaAirlineOnDL")+'</label></div>';
     str +='<div style="clear:both"></div></div>';
     str +='<div style="text-align:center;font-weight:bold"><label id="configcloser" style="cursor:pointer;">Close</label><div>';
     target.innerHTML=str;  
@@ -402,6 +406,7 @@
     document.getElementById('mptlaEdition').onclick=function(){toggleSettings("laEdition");};
     document.getElementById('mptlhEdition').onclick=function(){toggleSettings("lhEdition");};
     document.getElementById('mptlxEdition').onclick=function(){toggleSettings("lxEdition");};
+    document.getElementById('mptnonDeltaAirlineOnDL').onclick=function(){toggleSettings("nonDeltaAirlineOnDL");};
     document.getElementById('mptCabintoggler').onclick=function(){toggleSettings("cabin");};
     document.getElementById('configcloser').onclick=function(){toggleVis(document.getElementById("mptSettings"));};
     document.getElementById('mptStartparse').onclick=function(){document.getElementById('mptStartparse').style.display="none";setTimeout(function(){fePS();}, 50);}; 
@@ -2418,7 +2423,9 @@
           segcounter++; 
         }
       }
-      //deltaURL += "&cabin="+cabins[(mptSettings["cabin"]==="Auto" ? mincabin:getForcedCabin())];
+      if (mptUsersettings["nonDeltaAirlineOnDL"]==0) {
+        deltaURL += "&cabin="+cabins[(mptSettings["cabin"]==="Auto" ? mincabin:getForcedCabin())];
+      }
       deltaURL += "&fareBasis="+farebases.join(":");
       //deltaURL += "&price=0";
       deltaURL += "&numOfSegments=" + segcounter.toString() + "&paxCount=" + (pax.adults+pax.children.length+pax.infLap);
```

This seems to work correctly for the affected DL cabins.

**Comment by powerivq** [comment]
@seththeriault Thanks for the background. Let me test a few things out. I am not a huge believer of configurations when there is a potential that it can just work. I'm trying to see if we can only add the param for DL flights and make it work for both.

**Comment by seththeriault** [comment]
Any further thoughts on this?

**Comment by powerivq** [comment]
@seththeriault I see your PR (https://github.com/SteppoFF/ita-matrix-powertools/pull/28/files) appears to be working for both, so I think it's all good.

**Comment by seththeriault** [comment]
No, #28 is specifically broken by this PR as you commented out the cabin parameter in all DL URLs to allow non-DL airlines to be priced. The cabin classes are critical to correctly pricing DL flights.

I am happy to file an issue or another PR instead of going on in this thread.

**Pull request merged**
