### PR TITLE
Fix momondo, SkyScanner, and WhereToCredit

### PR DESCRIPTION
**Pull request by lensovet**
Just doing this on Benchmarc's behalf to get the fixes into the main repo

### CODE REVIEW

**Comment by lensovet** [comment]
ping @SteppoFF :)

**Comment by adamhwang** [comment]
Diff too large. Any way to get a smaller changeset? Otherwise I can take a look when I'm at a desktop

**Comment by lensovet** [comment]
should also update the minified version

**Comment by lensovet** [comment]
Looks like the majority of the diff here is whitespace changes. If you change the diff view settings to suppress those, it becomes much more manageable.

**Comment by adamhwang** [comment]
Thank you @lensovet!

**Comment by lensovet** [comment]
@adamhwang can you update the minified version? Not sure how to do that…

**Pull request merged**
