### PR TITLE
Update to version 0.35

### PR DESCRIPTION
**Pull request by wylek**
This pull request compiles several minor items I've been working on, enumerated below. Please let me know if you have any questions about them and I'd be happy to explain a bit more.

- bug fixes for QF
- minor UX changes for the settings panel
- bug fix for loading previously-saved user settings (when installed via userscript manager)
- added "Restore Defaults" option in the settings panel
- renamed LAN to LATAM and re-enabled with URL fixes
- pass cabin preference to Cheapoair, Expedia, Momondo, Skyscanner
- various JavaScript syntax modernization changes to improve readability
- changelog reformatted and older changes removed from header of main script to improve readability
- old (disabled) farefreaks functions moved to farefreaks_archived.js to reduce script size and load time

### CODE REVIEW

**Comment by adamhwang** [comment]
Thanks for taking the time to do this. Looks great

**Comment by reedy** [comment]
Wasn't sure the best place to report this, as issues aren't open, but they're "issues" caused by this PR

Any particular reason the minfied JS has gone from a single line to multiple ones? Change not mentioned in the changelog above, but it's been single line for aaaages

Also, this seems to cause browser console errors that weren't on the previous version (52e0de56c725711aae33ea272294dba9133a4fe7)

Screenshot 2019-12-09 at 19 30 08

```
Uncaught (in promise) ReferenceError: GM is not defined
    at <anonymous>:14:553
    at <anonymous>:16:24
(anonymous) @ VM145:14
(anonymous) @ VM145:16
VM145:53 empty
```

Chrome 78.0.3904.108 on macOS 10.14.6


Thanks!

**Comment by wylek** [comment]
> Any particular reason the minfied JS has gone from a single line to multiple ones? Change not mentioned in the changelog above, but it's been single line for aaaages

Good catch, my apologies. I messed up the minification and didn't notice. I'll get a new pull submitted to fix the minified script version. (I primarily use a userscript manager so I'll admit to not paying as much attention to the console version -- will be more mindful of that in the future when testing.)

**Comment by wylek** [comment]
New pull request submitted (#47). Thanks @reedy!

**Comment by reedy** [comment]
Sweet. Tested working. Thanks for the quick fix :)

**Pull request merged**
